name: Publish Package

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: DaVinciBot/shared-workflows/.github/workflows/publish-npm.yml@v5.0.0
    with:
      build_command: pnpm build
    secrets:
      PACKAGES_READ_TOKEN: ${{ secrets.PACKAGES_READ_TOKEN }}
